# .github/workflows/dispatch.yml
name: Dispatch to Bundle-Sync

on:
  push:
    branches:
      - 'rhoai-*'  # Adjust as needed for your branches

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository_dispatch to bundle-sync
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/DevOps-automation-tasks/bundle-sync/dispatches \
            -d '{"event_type": "sync", "client_payload": { "branch": "${GITHUB_REF#refs/heads/}" }}'
