name: Sync Bundle to RBC Repo

on:
  push:
    branches:
      - '**'  # Trigger on pushes to any branch
    paths:
      - 'bundle/**'
      - 'Dockerfiles/bundle.Dockerfile'
  pull_request:
    branches:
      - '**'  # Trigger on PRs targeting any branch
    paths:
      - 'bundle/**'
      - 'Dockerfiles/bundle.Dockerfile'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to sync'
        required: true
        type: string
  schedule:
    - cron: '0 0 * * *'  # Optional: Run on a schedule

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout rhods-operator repo
        uses: actions/checkout@v3
        with:
          repository: DevOps-automation-tasks/rhods-operator
          token: ${{ secrets.AUTOMATION_SYNC }}
          ref: ${{ github.event.inputs.branch || github.ref }}
          fetch-depth: 0  # Fetch all history

      - name: Debug Event Data
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Branch ref: ${{ github.ref }}"
          echo "Commit message: ${{ github.event.head_commit.message }}"
          echo "Event before: ${{ github.event.before }}"
          echo "Event after: ${{ github.event.after }}"
          echo "Files changed:"
          git fetch origin
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }}

      - name: Checkout RHOAI-Build-Config repo
        uses: actions/checkout@v3
        with:
          repository: DevOps-automation-tasks/RHOAI-Build-Config
          token: ${{ secrets.AUTOMATION_SYNC }}
          path: rbc_repo
          ref: ${{ github.event.inputs.branch || github.ref }}
          fetch-depth: 0  # Fetch all history

      - name: Sync bundle to RBC repo
        run: |
          mkdir -p rbc_repo/bundle/
          cp -r bundle/* rbc_repo/bundle/
          cp Dockerfiles/bundle.Dockerfile rbc_repo/bundle/Dockerfile
          echo "Files synced to RBC repo."

      - name: Update local branch and commit changes
        run: |
          cd rbc_repo
          git fetch origin
          git checkout ${{ github.event.inputs.branch || github.ref }}
          git pull origin ${{ github.event.inputs.branch || github.ref }}
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Sync bundle changes from rhods-operator repo" || echo "No changes to commit"

      - name: Push changes to RBC repo
        run: |
          cd rbc_repo
          git push origin ${{ github.event.inputs.branch || github.ref }}
